# Generated by Django 2.1.7 on 2019-05-21 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logger',
            options={'ordering': ('log',)},
        ),
        migrations.AddField(
            model_name='logger',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
